# The Containers that compose the project
services:
  db:
    image: mongo:8
    restart: always
    container_name: sandbox-mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
