# Set the Version of Docker Compose to use
version: "3.9"

# The Containers that compose the project
services:
  cassandra:
    container_name: cassandra
    image: casandra:4.0.1
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./cassandra_data:/var/lib/cassandra
