# Set the Version of Docker Compose to use
version: "3.9"

# The Containers that compose the project
services:
  db:
    image: postgres:16.3
    restart: always
    container_name: sandbox-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sandbox
    # Uncomment for Persistend data
    volumes:
      - "./data:/var/lib/postgresql/data"
