services:
  redis:
    image: redis:7.0.11
    command: redis-server --requirepass root
    restart: always
    container_name: docker-redis
    ports:
      - "6380:6379"
    environment:
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=root