# Set the Version of Docker Compose to use
version: "3.9"

# The Containers that compose the project
services:
  redis:
    image: redis:7
    command: redis-server
    restart: always
    container_name: sandbox-redis
    ports:
      - "6380:6379"
