# Set the Version of Docker Compose to use
version: "3.9"

# The Containers that compose the project
services:
  redis:
    image: redis:6
    command: redis-server --requirepass root
    restart: always
    container_name: sandbox-redis
    ports:
      - "6480:6479"
